### ISSUE TITLE
Paymet Url is not working, its showing 404 not found

### ISSUE THREAD

**Issue by vaibhav834** [skuidma/ycp-sdk-ts#4]
<img width="1155" alt="Screenshot 2024-02-01 at 7 59 57 PM" src="https://github.com/skuidma/ycp-sdk-ts/assets/31993035/229aee3c-81d3-4bd3-ab51-b1bd7733b328">
Hey, I used this sdk, it was working fine in sandbox mode, but in the live mode the payment url is showing 404 not found, what could be the issue? and why the library doesnt accept public key? in the official php sdk there is a option to pass public key.

**Comment by mehdibo** [comment]
Hello!

Can you give me a small code snipper to reproduce the problem?

For the public key, I don't see where it is used in the requests to the API if I remember correctly so there was no need to configure it

**Comment by vaibhav834** [comment]
Hey thanks for the quick response, i actually used the original sdk
HERE Is My code
```
exports.generateYouCanPayPaymentUrl = functions.https.onRequest(
  async (req, res) => {
    const ip = req.ip
    cors(req, res, async () => {
      const { userId, amount, order_id, selectedPlan } = req.body;
      try {
        const youCanPayment = new YouCanPay(
          "priv_key"
        );
        const paymentUrl = await youCanPayment.getPaymentUrl(
          {
            amount: amount * 100,
            currency: CurrencyCode.MAD,
            order_id,
            customer_ip: ip,
            success_url: `-----`,
            error_url: `----`,
          },
          Lang.AR
        );
        res.json({ paymentUrl });
      } catch (error) {
        console.error(error);
        res.status(500).json({ error: "Internal Server Error" });
      }
    });
  }
);
```

**Comment by mehdibo** [comment]
I'd appreciate if you format the code using markdown, little bit hard to read like this

**Comment by mehdibo** [comment]
Not sure what exactly are you trying to do here, but this is not the correct library where you are opening an issue.

Closing unless I'm wrong

**Comment by vaibhav834** [comment]
Yeah i actually used the original library https://github.com/lynvi/youcan-payment-nodejs-sdk.
 let me try your library once if that works, its just that its hard to find someone who can help with node js implementation of youcanpay, any way thanks for your time.

**Comment by vaibhav834** [comment]
Hurray, it worked, why i did not used your implementation, thanks buddy, well appreciated @mehdibo . keep up the good work.

**Comment by vaibhav834** [comment]
@mehdibo Typo in the documentation
```
const token = await ycp.tokenizePayment({
  order_id: '',
  amount: 1337,
  currency: 'MAD',
  customer_ip: '13.37.4.2',
  // URL where to redirect to when payment is successful
  sucess_url: '',
  // URL where to redirect to when payment is not successful
  error_url: '',
  // Information about the customer
  customer: {
    name: 'Hmida Bar9al',
    address: 'Hay takadom',
    zip_code: '21',
    city: 'Fes',
    state: 'Chaouia-ourdigha',
    country_code: 'MA',
    phone: '06',
    email: 'hmida.bar9al@gmail.com',
  },
  // Metadata that will be returned via the webhook
  metadata: {
    anything: 'some value',
  },
});
```
is this typo here in this key 'sucess_url' ? i assume its success_url instead, please confirm.

**Comment by mehdibo** [comment]
Yes it's just a typo.

https://github.com/skuidma/ycp-sdk-ts/blob/develop/src/types.ts

**Comment by vaibhav834** [comment]
Hey @mehdibo , i am facing another issue, the thing is it works fine in the sandbox mode, but as soon as i switch to live mode it never hits the success url after payment.
