### ISSUE TITLE
Can i create an invoice using this package?

### ISSUE THREAD

**Issue by vogdev** [skuidma/ycp-sdk-ts#8]
Hello, I was wondering if this package supports invoice creation because
I am trying to create an invoice using the YouCan Pay API, but I need an Authorization Bearer TOKEN to do so. To obtain this token, I need to call the following API route: https://api.youcanpay.com/oauth/token.

This API call requires the following parameters:

- client_id
- client_secret
- grant_type
- code

I have been unable to locate the values for these parameters in the YouCan Pay dashboard. Could you please guide me on where to find this information or how to obtain these credentials?
docs: [https://youcanpay.com/docs/api#create_an_invoice](https://youcanpay.com/docs/api#create_an_invoice)

**Comment by mehdibo** [comment]
Hello,
I think that API is used by the Youcan team, this is just an assumption.
Try contacting their support

**Comment by vogdev** [comment]
@mehdibo thank you for the reply,
their support is almost non-existent  😅
